--  tactical_objects_service.ads
--
--  EntityActions service interface for the Tactical Objects component,
--  aligned with the standard pyramid proto services:
--
--    Provided (proto/pyramid/components/tactical_objects/services/provided.proto):
--      Matching_Objects_Service      -- ReadMatch
--      Object_Of_Interest_Service    -- CRUD on ObjectInterestRequirement
--      Specific_Object_Detail_Service -- ReadDetail
--
--    Consumed (proto/pyramid/components/tactical_objects/services/consumed.proto):
--      Object_Evidence_Service          -- ReadDetail
--      Object_Solution_Evidence_Service -- CRUD on ObjectEvidenceRequirement
--      Object_Source_Capability_Service -- ReadCapability
--
--    Legacy (proto/pyramid/components/tactical_objects.proto):
--      TacticalObjectService, ZoneService, ObservationIngressService
--
--  The canonical generated spec (Handle_*/Dispatch) for each proto file lives
--  in examples/ada/generated/ (regenerated by ada_service_generator.py).
--
--  This file retains the transport-level helpers and the full set of channels
--  used by the demo clients.

with Tactical_Objects_Types;  use Tactical_Objects_Types;
with Streaming_Codec;
with System;

package Tactical_Objects_Service is

   --  -- EntityActions operation kind -----------------------------------------

   type Operation_Kind is
     (Op_Create,
      Op_Read,
      Op_Update,
      Op_Delete);

   -- =========================================================================
   --  Standard service channels (provided.proto + consumed.proto)
   -- =========================================================================

   --  Provided: Matching_Objects_Service
   type Provided_Matching_Channel is
     (Ch_Read_Match);

   --  Provided: Object_Of_Interest_Service
   type Provided_Interest_Channel is
     (Ch_Create_Requirement,
      Ch_Read_Requirement,
      Ch_Update_Requirement,
      Ch_Delete_Requirement);

   --  Provided: Specific_Object_Detail_Service
   type Provided_Detail_Channel is
     (Ch_Read_Detail);

   --  Consumed: Object_Evidence_Service
   type Consumed_Evidence_Channel is
     (Ch_Read_Evidence_Detail);

   --  Consumed: Object_Solution_Evidence_Service
   type Consumed_Solution_Channel is
     (Ch_Create_Evidence_Requirement,
      Ch_Read_Evidence_Requirement,
      Ch_Update_Evidence_Requirement,
      Ch_Delete_Evidence_Requirement);

   --  Consumed: Object_Source_Capability_Service
   type Consumed_Capability_Channel is
     (Ch_Read_Capability);

   -- =========================================================================
   --  Legacy service channels (tactical_objects.proto backward compat)
   -- =========================================================================

   type Service_Channel is
     (Ch_Create_Tactical_Object,
      Ch_Read_Tactical_Object,
      Ch_Update_Tactical_Object,
      Ch_Delete_Tactical_Object,
      Ch_Create_Zone,
      Ch_Read_Zone,
      Ch_Update_Zone,
      Ch_Delete_Zone,
      Ch_Create_Observation);

   --  Array types for streaming Read responses
   type Tactical_Object_Array is array (Positive range <>) of Tactical_Object;
   type Zone_Array            is array (Positive range <>) of Zone_Entity;
   type Object_Detail_Array   is array (Positive range <>) of Object_Detail;
   type Object_Match_Array    is array (Positive range <>) of Object_Match;

   -- =========================================================================
   --  Standard provided service handlers
   -- =========================================================================

   --  Matching_Objects_Service
   procedure Handle_Read_Match
     (Request  : in  Query;
      Response : out Object_Match_Array);

   --  Object_Of_Interest_Service
   procedure Handle_Create_Requirement
     (Request  : in  Object_Interest_Requirement;
      Response : out Identifier);

   procedure Handle_Read_Requirement
     (Request  : in  Query;
      Response : out Object_Interest_Requirement);

   procedure Handle_Update_Requirement
     (Request  : in  Object_Interest_Requirement;
      Response : out Ack);

   procedure Handle_Delete_Requirement
     (Request  : in  Identifier;
      Response : out Ack);

   --  Specific_Object_Detail_Service
   procedure Handle_Read_Detail
     (Request  : in  Query;
      Response : out Object_Detail_Array);

   -- =========================================================================
   --  Standard consumed service handlers
   -- =========================================================================

   --  Object_Evidence_Service
   procedure Handle_Read_Evidence_Detail
     (Request  : in  Query;
      Response : out Object_Detail_Array);

   --  Object_Solution_Evidence_Service
   procedure Handle_Create_Evidence_Requirement
     (Request  : in  Object_Evidence_Requirement;
      Response : out Identifier);

   procedure Handle_Read_Evidence_Requirement
     (Request  : in  Query;
      Response : out Object_Evidence_Requirement);

   procedure Handle_Update_Evidence_Requirement
     (Request  : in  Object_Evidence_Requirement;
      Response : out Ack);

   procedure Handle_Delete_Evidence_Requirement
     (Request  : in  Identifier;
      Response : out Ack);

   -- =========================================================================
   --  Legacy EntityActions handlers (TacticalObjectService, ZoneService, etc.)
   -- =========================================================================

   --  TacticalObjectService
   procedure Handle_Create_Tactical_Object
     (Request  : in  Tactical_Object;
      Response : out Identifier);

   procedure Handle_Read_Tactical_Object
     (Request  : in  Tactical_Object_Query;
      Response : out Tactical_Object_Array);

   procedure Handle_Update_Tactical_Object
     (Request  : in  Tactical_Object;
      Response : out Ack);

   procedure Handle_Delete_Tactical_Object
     (Request  : in  Identifier;
      Response : out Ack);

   --  ZoneService
   procedure Handle_Create_Zone
     (Request  : in  Zone_Entity;
      Response : out Identifier);

   procedure Handle_Read_Zone
     (Request  : in  Zone_Query;
      Response : out Zone_Array);

   procedure Handle_Update_Zone
     (Request  : in  Zone_Entity;
      Response : out Ack);

   procedure Handle_Delete_Zone
     (Request  : in  Identifier;
      Response : out Ack);

   --  ObservationIngressService
   procedure Handle_Create_Observation
     (Request  : in  Observation;
      Response : out Identifier);

   --  -- Transport integration point ------------------------------------------
   procedure Dispatch
     (Channel      : in  Service_Channel;
      Request_Buf  : in  System.Address;
      Request_Size : in  Natural;
      Response_Buf : out System.Address;
      Response_Size: out Natural);

   --  -- Transport-level helpers (used by ada_tobj_client) --------------------

   Read_Service_Name   : constant String := "subscribe_interest";
   Create_Service_Name : constant String := "create_object";
   Update_Service_Name : constant String := "update_object";
   Delete_Service_Name : constant String := "delete_object";

   function Build_Read_Request_Json
     (Query : Tactical_Object_Query) return String;

   function Build_Active_Find_Request_Json
     (Query : Tactical_Object_Query) return String;

   function Frame_To_Tactical_Object
     (Frame : Streaming_Codec.Entity_Update_Frame) return Tactical_Object;

   function Tactical_Object_Image
     (Obj : Tactical_Object) return String;

   function Ordinal_To_Affiliation
     (V : Streaming_Codec.Byte) return Affiliation;

   function Ordinal_To_Object_Type
     (V : Streaming_Codec.Byte) return Object_Type;

   function Ordinal_To_Lifecycle_Status
     (V : Streaming_Codec.Byte) return Lifecycle_Status;

end Tactical_Objects_Service;
