/// \file test_codec_dispatch_e2e.cpp
/// \brief E2E tests for multi-codec PCL communication.
///
/// Validates that two components can communicate via the codec dispatch layer
/// with different wire codecs configured per-port.
///
/// Test scenarios:
///   1. Publisher (JSON) → Subscriber (JSON): baseline round-trip
///   2. Content type propagation through pcl_msg_t
///   3. Per-port codec selection (JSON + FlatBuffers on different topics)
///   4. Default vs explicit codec on generated subscribe wrappers
///   5. JSON codec ser/de round-trip (unit-level, no PCL)
///   6. FlatBuffers-style binary codec pub/sub round-trip
///   7. Protobuf-style binary codec pub/sub round-trip
///   8. Three codecs on three ports, single executor
///   9. Codec mismatch detection (wrong deserialiser)
///
/// The codec dispatch layer routes serialisation based on pcl_msg_t.type_name,
/// which is set per-port at configure time.  Component business logic works
/// with typed structs and never touches raw bytes directly.
///
/// Architecture:
///   component logic → codec_dispatch::serialize() → pcl_msg_t → PCL executor
///   → subscriber callback → codec_dispatch::deserialize() → typed struct
///
/// Hand-written binary codecs:
///   Tests 6–8 implement a minimal binary codec for ObjectEvidence to
///   demonstrate how a real FlatBuffers/Protobuf codec would integrate.
///   The binary format is a simple packed struct — in production this would
///   be generated by flatc / protoc.
#include <gtest/gtest.h>

extern "C" {
#include <pcl/pcl_container.h>
#include <pcl/pcl_executor.h>
#include <pcl/pcl_types.h>
}

#include <atomic>
#include <cstring>
#include <string>
#include <vector>

// Generated service bindings (with content_type parameter)
#include "pyramid_services_tactical_objects_provided.hpp"
#include "pyramid_services_tactical_objects_consumed.hpp"
#include "pyramid_services_tactical_objects_json_codec.hpp"

namespace prov = pyramid::services::tactical_objects::provided;
namespace cons = pyramid::services::tactical_objects::consumed;
namespace codec = pyramid::services::tactical_objects::json_codec;

// ===========================================================================
// Hand-written binary codecs
//
// These simulate what generated FlatBuffers / Protobuf codecs would produce.
// The binary format is a simple packed struct with a 4-byte magic header
// so the deserialiser can validate it received the right codec's output.
// ===========================================================================

namespace {

// -- FlatBuffers-style binary codec ----------------------------------------
// Magic: "FLAT" (0x464C4154)
// Layout: [magic:4][identity:4][dimension:4][lat:8][lon:8][conf:8][obs:8]

constexpr uint32_t kFlatMagic = 0x464C4154;  // "FLAT"

#pragma pack(push, 1)
struct FlatObjectEvidence {
    uint32_t magic;
    int32_t  identity;
    int32_t  dimension;
    double   latitude_rad;
    double   longitude_rad;
    double   confidence;
    double   observed_at;
};
#pragma pack(pop)

std::string flatSerialize(const codec::ObjectEvidence& ev) {
    FlatObjectEvidence flat{};
    flat.magic         = kFlatMagic;
    flat.identity      = static_cast<int32_t>(ev.identity);
    flat.dimension     = static_cast<int32_t>(ev.dimension);
    flat.latitude_rad  = ev.latitude_rad;
    flat.longitude_rad = ev.longitude_rad;
    flat.confidence    = ev.confidence;
    flat.observed_at   = ev.observed_at;
    return std::string(reinterpret_cast<const char*>(&flat), sizeof(flat));
}

bool flatDeserialize(const void* data, size_t size, codec::ObjectEvidence& out) {
    if (size < sizeof(FlatObjectEvidence)) return false;
    FlatObjectEvidence flat;
    std::memcpy(&flat, data, sizeof(flat));
    if (flat.magic != kFlatMagic) return false;
    out.identity      = static_cast<codec::StandardIdentity>(flat.identity);
    out.dimension     = static_cast<codec::BattleDimension>(flat.dimension);
    out.latitude_rad  = flat.latitude_rad;
    out.longitude_rad = flat.longitude_rad;
    out.confidence    = flat.confidence;
    out.observed_at   = flat.observed_at;
    return true;
}

// -- Protobuf-style binary codec ------------------------------------------
// Magic: "PRBF" (0x50524246)
// Same layout but different magic, simulating a distinct codec backend.

constexpr uint32_t kProtoMagic = 0x50524246;  // "PRBF"

#pragma pack(push, 1)
struct ProtoObjectEvidence {
    uint32_t magic;
    int32_t  identity;
    int32_t  dimension;
    double   latitude_rad;
    double   longitude_rad;
    double   confidence;
    double   observed_at;
};
#pragma pack(pop)

std::string protoSerialize(const codec::ObjectEvidence& ev) {
    ProtoObjectEvidence pb{};
    pb.magic         = kProtoMagic;
    pb.identity      = static_cast<int32_t>(ev.identity);
    pb.dimension     = static_cast<int32_t>(ev.dimension);
    pb.latitude_rad  = ev.latitude_rad;
    pb.longitude_rad = ev.longitude_rad;
    pb.confidence    = ev.confidence;
    pb.observed_at   = ev.observed_at;
    return std::string(reinterpret_cast<const char*>(&pb), sizeof(pb));
}

bool protoDeserialize(const void* data, size_t size, codec::ObjectEvidence& out) {
    if (size < sizeof(ProtoObjectEvidence)) return false;
    ProtoObjectEvidence pb;
    std::memcpy(&pb, data, sizeof(pb));
    if (pb.magic != kProtoMagic) return false;
    out.identity      = static_cast<codec::StandardIdentity>(pb.identity);
    out.dimension     = static_cast<codec::BattleDimension>(pb.dimension);
    out.latitude_rad  = pb.latitude_rad;
    out.longitude_rad = pb.longitude_rad;
    out.confidence    = pb.confidence;
    out.observed_at   = pb.observed_at;
    return true;
}

// -- Multi-codec dispatch helper ------------------------------------------
// Routes serialize/deserialize based on content_type string, exactly as
// the generated codec_dispatch.hpp would.

std::string serializeEvidence(const codec::ObjectEvidence& ev,
                              const char* content_type) {
    if (std::strcmp(content_type, "application/json") == 0)
        return codec::toJson(ev);
    if (std::strcmp(content_type, "application/flatbuffers") == 0)
        return flatSerialize(ev);
    if (std::strcmp(content_type, "application/protobuf") == 0)
        return protoSerialize(ev);
    return {};
}

bool deserializeEvidence(const void* data, size_t size,
                         const char* content_type,
                         codec::ObjectEvidence& out) {
    if (std::strcmp(content_type, "application/json") == 0) {
        out = codec::objectEvidenceFromJson(
            std::string(static_cast<const char*>(data), size));
        return true;
    }
    if (std::strcmp(content_type, "application/flatbuffers") == 0)
        return flatDeserialize(data, size, out);
    if (std::strcmp(content_type, "application/protobuf") == 0)
        return protoDeserialize(data, size, out);
    return false;
}

// ===========================================================================
// Shared test infrastructure
// ===========================================================================

// Reference evidence message used across tests
codec::ObjectEvidence makeTestEvidence() {
    codec::ObjectEvidence ev;
    ev.identity      = codec::StandardIdentity::Hostile;
    ev.dimension     = codec::BattleDimension::SeaSurface;
    ev.latitude_rad  = 0.8901;
    ev.longitude_rad = 0.0012;
    ev.confidence    = 0.95;
    ev.observed_at   = 1.5;
    return ev;
}

void expectEvidenceEqual(const codec::ObjectEvidence& a,
                         const codec::ObjectEvidence& b) {
    EXPECT_EQ(a.identity,  b.identity);
    EXPECT_EQ(a.dimension, b.dimension);
    EXPECT_DOUBLE_EQ(a.latitude_rad,  b.latitude_rad);
    EXPECT_DOUBLE_EQ(a.longitude_rad, b.longitude_rad);
    EXPECT_DOUBLE_EQ(a.confidence,    b.confidence);
    EXPECT_DOUBLE_EQ(a.observed_at,   b.observed_at);
}

// State for a pub/sub pair that dispatches via the multi-codec helper
struct CodecPubSubState {
    pcl_port_t* pub_port = nullptr;
    std::string content_type = "application/json";

    std::atomic<int>  messages_received{0};
    std::string       last_type_name;
    codec::ObjectEvidence received{};
    bool              deserialize_ok = false;
};

void codec_sub_cb(pcl_container_t*, const pcl_msg_t* msg, void* ud) {
    auto* st = static_cast<CodecPubSubState*>(ud);
    if (!msg || !msg->data || msg->size == 0) return;

    st->last_type_name = msg->type_name ? msg->type_name : "";
    st->deserialize_ok = deserializeEvidence(
        msg->data, msg->size, st->last_type_name.c_str(), st->received);
    st->messages_received.fetch_add(1);
}

pcl_status_t configure_codec_pub(pcl_container_t* c, void* ud) {
    auto* st = static_cast<CodecPubSubState*>(ud);
    st->pub_port = pcl_container_add_publisher(
        c, cons::kTopicObjectEvidence, st->content_type.c_str());
    return PCL_OK;
}

pcl_status_t configure_codec_sub(pcl_container_t* c, void* ud) {
    auto* st = static_cast<CodecPubSubState*>(ud);
    cons::subscribeObjectEvidence(c, codec_sub_cb, ud, st->content_type.c_str());
    return PCL_OK;
}

// Helper: run a pub/sub round-trip with the given content_type
void runPubSubRoundTrip(const char* content_type,
                        const codec::ObjectEvidence& evidence) {
    CodecPubSubState state;
    state.content_type = content_type;

    pcl_executor_t* exec = pcl_executor_create();
    ASSERT_NE(exec, nullptr);

    // Publisher
    pcl_callbacks_t pub_cbs{};
    pub_cbs.on_configure = configure_codec_pub;
    std::string pub_name = std::string("pub_") + content_type;
    pcl_container_t* pub_c =
        pcl_container_create(pub_name.c_str(), &pub_cbs, &state);
    ASSERT_NE(pub_c, nullptr);
    pcl_container_configure(pub_c);
    pcl_container_activate(pub_c);
    pcl_executor_add(exec, pub_c);

    // Subscriber
    pcl_callbacks_t sub_cbs{};
    sub_cbs.on_configure = configure_codec_sub;
    std::string sub_name = std::string("sub_") + content_type;
    pcl_container_t* sub_c =
        pcl_container_create(sub_name.c_str(), &sub_cbs, &state);
    ASSERT_NE(sub_c, nullptr);
    pcl_container_configure(sub_c);
    pcl_container_activate(sub_c);
    pcl_executor_add(exec, sub_c);

    // Serialize and publish
    std::string payload = serializeEvidence(evidence, content_type);
    ASSERT_FALSE(payload.empty()) << "serialization failed for " << content_type;

    pcl_status_t rc = cons::publishObjectEvidence(
        state.pub_port, payload, content_type);
    ASSERT_EQ(rc, PCL_OK);

    // Spin to deliver
    for (int i = 0; i < 10; ++i) {
        pcl_executor_spin_once(exec, 0);
        if (state.messages_received.load() > 0) break;
    }

    ASSERT_GE(state.messages_received.load(), 1)
        << "no message received for " << content_type;
    EXPECT_EQ(state.last_type_name, content_type);
    EXPECT_TRUE(state.deserialize_ok)
        << "deserialization failed for " << content_type;
    expectEvidenceEqual(state.received, evidence);

    pcl_executor_destroy(exec);
    pcl_container_destroy(sub_c);
    pcl_container_destroy(pub_c);
}

}  // namespace

// ===========================================================================
// Test 1: JSON pub/sub round-trip
// ===========================================================================

TEST(CodecDispatchE2E, JsonPubSubRoundTrip) {
    runPubSubRoundTrip("application/json", makeTestEvidence());
}

// ===========================================================================
// Test 2: FlatBuffers binary codec pub/sub round-trip
//
// Hand-written FlatBuffers-style codec serialises ObjectEvidence into a
// packed binary struct.  The subscriber deserialises using the same codec,
// selected by content_type = "application/flatbuffers".
// ===========================================================================

TEST(CodecDispatchE2E, FlatBuffersPubSubRoundTrip) {
    runPubSubRoundTrip("application/flatbuffers", makeTestEvidence());
}

// ===========================================================================
// Test 3: Protobuf binary codec pub/sub round-trip
//
// Hand-written Protobuf-style codec with its own magic header.
// ===========================================================================

TEST(CodecDispatchE2E, ProtobufPubSubRoundTrip) {
    runPubSubRoundTrip("application/protobuf", makeTestEvidence());
}

// ===========================================================================
// Test 4: Content type propagation
//
// Verify that the content_type string set at port creation time is correctly
// propagated through pcl_msg_t.type_name to the subscriber callback.
// ===========================================================================

TEST(CodecDispatchE2E, ContentTypePropagation) {
    CodecPubSubState state;
    state.content_type = "application/flatbuffers";

    pcl_executor_t* exec = pcl_executor_create();
    ASSERT_NE(exec, nullptr);

    pcl_callbacks_t pub_cbs{};
    pub_cbs.on_configure = configure_codec_pub;
    pcl_container_t* pub_c =
        pcl_container_create("fb_publisher", &pub_cbs, &state);
    ASSERT_NE(pub_c, nullptr);
    pcl_container_configure(pub_c);
    pcl_container_activate(pub_c);
    pcl_executor_add(exec, pub_c);

    pcl_callbacks_t sub_cbs{};
    sub_cbs.on_configure = configure_codec_sub;
    pcl_container_t* sub_c =
        pcl_container_create("fb_subscriber", &sub_cbs, &state);
    ASSERT_NE(sub_c, nullptr);
    pcl_container_configure(sub_c);
    pcl_container_activate(sub_c);
    pcl_executor_add(exec, sub_c);

    // Publish binary payload
    auto ev = makeTestEvidence();
    std::string payload = flatSerialize(ev);
    pcl_status_t rc = cons::publishObjectEvidence(
        state.pub_port, payload, "application/flatbuffers");
    ASSERT_EQ(rc, PCL_OK);

    for (int i = 0; i < 10; ++i) {
        pcl_executor_spin_once(exec, 0);
        if (state.messages_received.load() > 0) break;
    }

    EXPECT_GE(state.messages_received.load(), 1);
    EXPECT_EQ(state.last_type_name, "application/flatbuffers");
    EXPECT_EQ(sizeof(FlatObjectEvidence), payload.size());

    pcl_executor_destroy(exec);
    pcl_container_destroy(sub_c);
    pcl_container_destroy(pub_c);
}

// ===========================================================================
// Test 5: Per-port codec selection — three codecs on three ports
//
// A single publisher container has three ports, one per codec.
// A single subscriber container subscribes to all three.
// Each subscriber verifies it received the correct content_type and that
// the payload deserialises correctly with the matching codec.
// ===========================================================================

namespace {

struct ThreeCodecState {
    // Publishers (one per codec)
    pcl_port_t* json_pub = nullptr;
    pcl_port_t* flat_pub = nullptr;
    pcl_port_t* proto_pub = nullptr;

    // Subscriber receives
    struct Received {
        std::atomic<int>    count{0};
        std::string         type_name;
        codec::ObjectEvidence evidence{};
        bool                ok = false;
    };
    Received json_rx, flat_rx, proto_rx;
};

void on_json_rx(pcl_container_t*, const pcl_msg_t* msg, void* ud) {
    auto* st = static_cast<ThreeCodecState*>(ud);
    if (!msg || !msg->data) return;
    st->json_rx.type_name = msg->type_name ? msg->type_name : "";
    st->json_rx.ok = deserializeEvidence(
        msg->data, msg->size, "application/json", st->json_rx.evidence);
    st->json_rx.count.fetch_add(1);
}

void on_flat_rx(pcl_container_t*, const pcl_msg_t* msg, void* ud) {
    auto* st = static_cast<ThreeCodecState*>(ud);
    if (!msg || !msg->data) return;
    st->flat_rx.type_name = msg->type_name ? msg->type_name : "";
    st->flat_rx.ok = deserializeEvidence(
        msg->data, msg->size, "application/flatbuffers", st->flat_rx.evidence);
    st->flat_rx.count.fetch_add(1);
}

void on_proto_rx(pcl_container_t*, const pcl_msg_t* msg, void* ud) {
    auto* st = static_cast<ThreeCodecState*>(ud);
    if (!msg || !msg->data) return;
    st->proto_rx.type_name = msg->type_name ? msg->type_name : "";
    st->proto_rx.ok = deserializeEvidence(
        msg->data, msg->size, "application/protobuf", st->proto_rx.evidence);
    st->proto_rx.count.fetch_add(1);
}

pcl_status_t configure_three_pub(pcl_container_t* c, void* ud) {
    auto* st = static_cast<ThreeCodecState*>(ud);
    st->json_pub  = pcl_container_add_publisher(c, "test.json",  "application/json");
    st->flat_pub  = pcl_container_add_publisher(c, "test.flat",  "application/flatbuffers");
    st->proto_pub = pcl_container_add_publisher(c, "test.proto", "application/protobuf");
    return PCL_OK;
}

pcl_status_t configure_three_sub(pcl_container_t* c, void* ud) {
    pcl_container_add_subscriber(c, "test.json",  "application/json",        on_json_rx,  ud);
    pcl_container_add_subscriber(c, "test.flat",  "application/flatbuffers", on_flat_rx,  ud);
    pcl_container_add_subscriber(c, "test.proto", "application/protobuf",    on_proto_rx, ud);
    return PCL_OK;
}

}  // namespace

TEST(CodecDispatchE2E, ThreeCodecsThreePorts) {
    ThreeCodecState state;
    auto ev = makeTestEvidence();

    pcl_executor_t* exec = pcl_executor_create();
    ASSERT_NE(exec, nullptr);

    // Publisher
    pcl_callbacks_t pub_cbs{};
    pub_cbs.on_configure = configure_three_pub;
    pcl_container_t* pub_c =
        pcl_container_create("three_pub", &pub_cbs, &state);
    ASSERT_NE(pub_c, nullptr);
    pcl_container_configure(pub_c);
    pcl_container_activate(pub_c);
    pcl_executor_add(exec, pub_c);

    // Subscriber
    pcl_callbacks_t sub_cbs{};
    sub_cbs.on_configure = configure_three_sub;
    pcl_container_t* sub_c =
        pcl_container_create("three_sub", &sub_cbs, &state);
    ASSERT_NE(sub_c, nullptr);
    pcl_container_configure(sub_c);
    pcl_container_activate(sub_c);
    pcl_executor_add(exec, sub_c);

    // Publish on all three topics, each with its own codec
    {
        std::string p = codec::toJson(ev);
        pcl_msg_t msg{};
        msg.data = p.data();
        msg.size = static_cast<uint32_t>(p.size());
        msg.type_name = "application/json";
        pcl_port_publish(state.json_pub, &msg);
    }
    {
        std::string p = flatSerialize(ev);
        pcl_msg_t msg{};
        msg.data = p.data();
        msg.size = static_cast<uint32_t>(p.size());
        msg.type_name = "application/flatbuffers";
        pcl_port_publish(state.flat_pub, &msg);
    }
    {
        std::string p = protoSerialize(ev);
        pcl_msg_t msg{};
        msg.data = p.data();
        msg.size = static_cast<uint32_t>(p.size());
        msg.type_name = "application/protobuf";
        pcl_port_publish(state.proto_pub, &msg);
    }

    // Spin to deliver all three
    for (int i = 0; i < 20; ++i) {
        pcl_executor_spin_once(exec, 0);
        if (state.json_rx.count.load() > 0 &&
            state.flat_rx.count.load() > 0 &&
            state.proto_rx.count.load() > 0)
            break;
    }

    // Verify JSON
    ASSERT_GE(state.json_rx.count.load(), 1);
    EXPECT_EQ(state.json_rx.type_name, "application/json");
    EXPECT_TRUE(state.json_rx.ok);
    expectEvidenceEqual(state.json_rx.evidence, ev);

    // Verify FlatBuffers
    ASSERT_GE(state.flat_rx.count.load(), 1);
    EXPECT_EQ(state.flat_rx.type_name, "application/flatbuffers");
    EXPECT_TRUE(state.flat_rx.ok);
    expectEvidenceEqual(state.flat_rx.evidence, ev);

    // Verify Protobuf
    ASSERT_GE(state.proto_rx.count.load(), 1);
    EXPECT_EQ(state.proto_rx.type_name, "application/protobuf");
    EXPECT_TRUE(state.proto_rx.ok);
    expectEvidenceEqual(state.proto_rx.evidence, ev);

    pcl_executor_destroy(exec);
    pcl_container_destroy(sub_c);
    pcl_container_destroy(pub_c);
}

// ===========================================================================
// Test 6: Codec mismatch detection
//
// Publish with FlatBuffers codec but attempt to deserialise as Protobuf.
// The magic header should cause deserialisation to fail gracefully.
// ===========================================================================

TEST(CodecDispatchE2E, CodecMismatchDetection) {
    auto ev = makeTestEvidence();

    // Serialize as FlatBuffers
    std::string flat_payload = flatSerialize(ev);

    // Try to deserialize as Protobuf — should fail (wrong magic)
    codec::ObjectEvidence out{};
    bool ok = protoDeserialize(flat_payload.data(), flat_payload.size(), out);
    EXPECT_FALSE(ok) << "protobuf deserializer should reject flatbuffers data";

    // Try to deserialize as FlatBuffers — should succeed
    ok = flatDeserialize(flat_payload.data(), flat_payload.size(), out);
    EXPECT_TRUE(ok);
    expectEvidenceEqual(out, ev);

    // Serialize as Protobuf
    std::string proto_payload = protoSerialize(ev);

    // Try to deserialize as FlatBuffers — should fail
    ok = flatDeserialize(proto_payload.data(), proto_payload.size(), out);
    EXPECT_FALSE(ok) << "flatbuffers deserializer should reject protobuf data";
}

// ===========================================================================
// Test 7: Binary payload size verification
//
// Verify that binary codecs produce smaller payloads than JSON for the
// same message — a key reason for using binary codecs.
// ===========================================================================

TEST(CodecDispatchE2E, BinaryCodecsSmallerThanJson) {
    auto ev = makeTestEvidence();

    std::string json_payload  = codec::toJson(ev);
    std::string flat_payload  = flatSerialize(ev);
    std::string proto_payload = protoSerialize(ev);

    // Binary formats should be smaller than JSON
    EXPECT_LT(flat_payload.size(), json_payload.size())
        << "FlatBuffers payload should be smaller than JSON";
    EXPECT_LT(proto_payload.size(), json_payload.size())
        << "Protobuf payload should be smaller than JSON";

    // Both binary formats have the same size (same struct layout)
    EXPECT_EQ(flat_payload.size(), proto_payload.size());

    // Verify exact binary size: 4 (magic) + 4 + 4 + 8*4 = 44 bytes
    EXPECT_EQ(flat_payload.size(), sizeof(FlatObjectEvidence));
    EXPECT_EQ(proto_payload.size(), sizeof(ProtoObjectEvidence));
}

// ===========================================================================
// Test 8: Default codec is JSON (backwards compatibility)
// ===========================================================================

namespace {

struct ServiceCodecState {
    std::string subscribed_type;
};

void svc_sub_cb(pcl_container_t*, const pcl_msg_t* msg, void* ud) {
    auto* st = static_cast<ServiceCodecState*>(ud);
    if (msg && msg->type_name)
        st->subscribed_type = msg->type_name;
}

pcl_status_t configure_default_codec(pcl_container_t* c, void* ud) {
    // Call without content_type — should default to "application/json"
    prov::subscribeEntityMatches(c, svc_sub_cb, ud);
    return PCL_OK;
}

pcl_status_t configure_explicit_codec(pcl_container_t* c, void* ud) {
    // Call with explicit content_type
    prov::subscribeEntityMatches(c, svc_sub_cb, ud,
                                 "application/protobuf");
    return PCL_OK;
}

}  // namespace

TEST(CodecDispatchE2E, DefaultCodecIsJson) {
    ServiceCodecState state;
    pcl_callbacks_t cbs{};
    cbs.on_configure = configure_default_codec;

    pcl_container_t* c = pcl_container_create("default_codec", &cbs, &state);
    ASSERT_NE(c, nullptr);
    pcl_container_configure(c);
    pcl_container_activate(c);

    pcl_executor_t* exec = pcl_executor_create();
    pcl_executor_add(exec, c);

    pcl_msg_t msg{};
    std::string payload = "test";
    msg.data = payload.data();
    msg.size = static_cast<uint32_t>(payload.size());
    msg.type_name = "application/json";
    pcl_executor_dispatch_incoming(exec, prov::kTopicEntityMatches, &msg);
    pcl_executor_spin_once(exec, 0);

    EXPECT_EQ(state.subscribed_type, "application/json");

    pcl_executor_destroy(exec);
    pcl_container_destroy(c);
}

// ===========================================================================
// Test 9: Explicit protobuf codec on generated wrapper
// ===========================================================================

TEST(CodecDispatchE2E, ExplicitCodecProtobuf) {
    ServiceCodecState state;
    pcl_callbacks_t cbs{};
    cbs.on_configure = configure_explicit_codec;

    pcl_container_t* c = pcl_container_create("explicit_codec", &cbs, &state);
    ASSERT_NE(c, nullptr);
    pcl_container_configure(c);
    pcl_container_activate(c);

    pcl_executor_t* exec = pcl_executor_create();
    pcl_executor_add(exec, c);

    // Dispatch with protobuf content type
    auto ev = makeTestEvidence();
    std::string payload = protoSerialize(ev);
    pcl_msg_t msg{};
    msg.data = payload.data();
    msg.size = static_cast<uint32_t>(payload.size());
    msg.type_name = "application/protobuf";
    pcl_executor_dispatch_incoming(exec, prov::kTopicEntityMatches, &msg);
    pcl_executor_spin_once(exec, 0);

    EXPECT_EQ(state.subscribed_type, "application/protobuf");

    pcl_executor_destroy(exec);
    pcl_container_destroy(c);
}

// ===========================================================================
// Test 10: JSON codec ser/de round-trip (unit-level, no PCL)
// ===========================================================================

TEST(CodecDispatchE2E, JsonCodecSerDeRoundTrip) {
    codec::CreateRequirementRequest req;
    req.policy      = codec::DataPolicy::Obtain;
    req.identity    = codec::StandardIdentity::Hostile;
    req.dimension   = codec::BattleDimension::SeaSurface;
    req.min_lat_rad = 0.873;
    req.max_lat_rad = 0.907;
    req.min_lon_rad = -0.017;
    req.max_lon_rad = 0.017;

    std::string json_str = codec::toJson(req);
    EXPECT_FALSE(json_str.empty());

    auto req2 = codec::createRequirementRequestFromJson(json_str);

    EXPECT_EQ(req2.policy,      codec::DataPolicy::Obtain);
    EXPECT_EQ(req2.identity,    codec::StandardIdentity::Hostile);
    EXPECT_EQ(req2.dimension,   codec::BattleDimension::SeaSurface);
    EXPECT_DOUBLE_EQ(req2.min_lat_rad, 0.873);
    EXPECT_DOUBLE_EQ(req2.max_lat_rad, 0.907);
    EXPECT_DOUBLE_EQ(req2.min_lon_rad, -0.017);
    EXPECT_DOUBLE_EQ(req2.max_lon_rad, 0.017);
}

// ===========================================================================
// Test 11: Enum string round-trip
// ===========================================================================

TEST(CodecDispatchE2E, JsonCodecEnumRoundTrip) {
    const codec::StandardIdentity identities[] = {
        codec::StandardIdentity::Unspecified,
        codec::StandardIdentity::Unknown,
        codec::StandardIdentity::Friendly,
        codec::StandardIdentity::Hostile,
        codec::StandardIdentity::Suspect,
        codec::StandardIdentity::Neutral,
        codec::StandardIdentity::Pending,
        codec::StandardIdentity::Joker,
        codec::StandardIdentity::Faker,
        codec::StandardIdentity::AssumedFriendly,
    };

    for (auto id : identities) {
        std::string s = codec::toString(id);
        EXPECT_FALSE(s.empty()) << "toString returned empty for ordinal "
                                << static_cast<int>(id);
        auto roundtripped = codec::standardIdentityFromString(s);
        EXPECT_EQ(roundtripped, id)
            << "Round-trip failed for " << s;
    }
}

// ===========================================================================
// Test 12: FlatBuffers binary codec ser/de unit test (no PCL)
// ===========================================================================

TEST(CodecDispatchE2E, FlatBuffersCodecUnitRoundTrip) {
    auto ev = makeTestEvidence();

    std::string payload = flatSerialize(ev);
    EXPECT_EQ(payload.size(), sizeof(FlatObjectEvidence));

    codec::ObjectEvidence out{};
    bool ok = flatDeserialize(payload.data(), payload.size(), out);
    ASSERT_TRUE(ok);
    expectEvidenceEqual(out, ev);
}

// ===========================================================================
// Test 13: Protobuf binary codec ser/de unit test (no PCL)
// ===========================================================================

TEST(CodecDispatchE2E, ProtobufCodecUnitRoundTrip) {
    auto ev = makeTestEvidence();

    std::string payload = protoSerialize(ev);
    EXPECT_EQ(payload.size(), sizeof(ProtoObjectEvidence));

    codec::ObjectEvidence out{};
    bool ok = protoDeserialize(payload.data(), payload.size(), out);
    ASSERT_TRUE(ok);
    expectEvidenceEqual(out, ev);
}

// ===========================================================================
// Test 14: Cross-codec field fidelity
//
// Serialize the same message with all three codecs, deserialize each,
// and verify all three produce identical typed structs.
// ===========================================================================

TEST(CodecDispatchE2E, CrossCodecFieldFidelity) {
    auto ev = makeTestEvidence();

    // Serialize with all three codecs
    std::string json_bytes  = serializeEvidence(ev, "application/json");
    std::string flat_bytes  = serializeEvidence(ev, "application/flatbuffers");
    std::string proto_bytes = serializeEvidence(ev, "application/protobuf");

    // Deserialize each
    codec::ObjectEvidence from_json{}, from_flat{}, from_proto{};
    ASSERT_TRUE(deserializeEvidence(json_bytes.data(), json_bytes.size(),
                                     "application/json", from_json));
    ASSERT_TRUE(deserializeEvidence(flat_bytes.data(), flat_bytes.size(),
                                     "application/flatbuffers", from_flat));
    ASSERT_TRUE(deserializeEvidence(proto_bytes.data(), proto_bytes.size(),
                                     "application/protobuf", from_proto));

    // All three must produce identical results
    expectEvidenceEqual(from_json, ev);
    expectEvidenceEqual(from_flat, ev);
    expectEvidenceEqual(from_proto, ev);
}
