#!/usr/bin/env python3
"""
Ada Service Stub Generator
Generates PCL-aligned EntityActions service stubs from a .proto IDL file.

Each rpc in a proto service block produces a Handle_<Op>_<Entity> procedure
matching the EntityActions CRUD contract:

  CreateXxx(Xxx)            returns (Identifier)   -> Handle_Create_Xxx
  ReadXxx(XxxQuery)         returns (stream Xxx)   -> Handle_Read_Xxx
  UpdateXxx(Xxx)            returns (Ack)           -> Handle_Update_Xxx
  DeleteXxx(Identifier)     returns (Ack)           -> Handle_Delete_Xxx

A Dispatch procedure is generated as the single integration point for any
transport (PCL, socket, shared memory, etc.) -- it routes an incoming
operation+channel to the correct typed handler.

Generated packages reference the types package derived from the proto file.

Service wire-name constants and PCL binding procedures
(Subscribe_*, Invoke_*, Publish_*) are generated for standard pyramid protocol
interaction.  JSON serialisation/deserialisation is delegated entirely to the
companion Json_Codec package generated by JsonCodecGenerator (see below).

Canonical JSON wire format is defined in json_schema.py.

Architecture: component logic > service binding (this layer) > pcl

Usage:
    python ada_service_generator.py <file.proto> <output_dir>
    python ada_service_generator.py <proto_dir/>  <output_dir>

    # Also generate the JSON codec package:
    python ada_service_generator.py --codec <file.proto> <output_dir>
"""

import sys
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Import canonical schema — also used by JsonCodecGenerator below
import json_schema as schema
from proto_parser import (
    parse_proto_tree, ProtoTypeIndex, ProtoMessage, ProtoEnum,
    screaming_to_pascal, camel_to_snake, _PROTO_SCALARS,
)


# -- EntityActions operation set -----------------------------------------------

OP_PREFIXES = ['Create', 'Read', 'Update', 'Delete']

# Base-type short names from pyramid.data_model.base.* and common.*
BASE_TYPE_MAP = {
    'pyramid.data_model.base.Identifier': 'Identifier',
    'pyramid.data_model.base.Query':      'Query',
    'pyramid.data_model.base.Ack':        'Ack',
    'pyramid.data_model.common.Query':    'Query',
    'pyramid.data_model.common.Ack':      'Ack',
    'pyramid.data_model.common.Capability': 'Identifier',
}

# Wire-name service prefix derived from proto service name
# e.g. Object_Of_Interest_Service -> "object_of_interest"
# RPC CreateRequirement -> "create_requirement"
# Full wire name: "object_of_interest.create_requirement"

# Standard topic names — sourced from json_schema.py as canonical authority.
#
# SUBSCRIBE_TOPICS: topics the Ada client SUBSCRIBES to (server publishes).
#   Generated on the "provided" service binding package.
# PUBLISH_TOPICS:   topics the Ada client PUBLISHES to (server subscribes).
#   Generated on the "consumed" service binding package.
SUBSCRIBE_TOPICS = schema.SUBSCRIBE_TOPICS   # entity_matches, evidence_requirements
PUBLISH_TOPICS   = schema.PUBLISH_TOPICS     # object_evidence


# -- Proto parser --------------------------------------------------------------

def _strip_comments(text: str) -> str:
    """Remove // line comments and /* */ block comments."""
    text = re.sub(r'//[^\n]*', '', text)
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
    return text


def _camel_to_snake(name: str) -> str:
    """TacticalObject -> Tactical_Object  (Ada identifier style)."""
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s)
    return s


def _camel_to_lower_snake(name: str) -> str:
    """ObjectOfInterest -> object_of_interest (wire-format style)."""
    return _camel_to_snake(name).lower()


def _short_type(full_type: str) -> str:
    """pyramid.data_model.base.Identifier -> Identifier."""
    if full_type in BASE_TYPE_MAP:
        return BASE_TYPE_MAP[full_type]
    return full_type.split('.')[-1]


def _proto_type_to_ada(full_type: str) -> str:
    """Map a proto type to its Ada equivalent in Tactical_Objects_Types."""
    short = _short_type(full_type)
    # Apply CamelCase -> Ada_Style conversion for compound names
    return _camel_to_snake(short)


def _service_wire_prefix(service_name: str) -> str:
    """Object_Of_Interest_Service -> object_of_interest."""
    # Remove _Service suffix if present
    name = service_name
    if name.endswith('_Service'):
        name = name[:-len('_Service')]
    return _camel_to_lower_snake(name)


class ProtoRpc:
    """One rpc entry extracted from a proto service block."""

    def __init__(self, name: str, req: str, rsp: str, streaming: bool):
        self.name = name
        self.req = req
        self.rsp = rsp
        self.streaming = streaming

        self.op: Optional[str] = None
        self.entity: Optional[str] = None
        for prefix in OP_PREFIXES:
            if name.startswith(prefix):
                self.op = prefix
                self.entity = name[len(prefix):]
                break

    @property
    def ada_handler(self) -> str:
        return f'Handle_{self.op}_{_camel_to_snake(self.entity)}'

    @property
    def ada_channel(self) -> str:
        return f'Ch_{self.op}_{_camel_to_snake(self.entity)}'

    @property
    def ada_req_type(self) -> str:
        return _proto_type_to_ada(self.req)

    @property
    def ada_rsp_type(self) -> str:
        base = _proto_type_to_ada(self.rsp)
        if self.streaming:
            return f'{base}_Array'
        return base

    @property
    def wire_name(self) -> str:
        """create_requirement (rpc part of wire name)."""
        return _camel_to_lower_snake(self.name)

    @property
    def ada_invoke_name(self) -> str:
        """Invoke_Create_Requirement."""
        return f'Invoke_{_camel_to_snake(self.name)}'

    @property
    def ada_svc_const(self) -> str:
        """Svc_Create_Requirement."""
        return f'Svc_{_camel_to_snake(self.name)}'


class ProtoService:
    def __init__(self, name: str, rpcs: List[ProtoRpc]):
        self.name = name
        self.rpcs = [r for r in rpcs if r.op is not None]

    @property
    def wire_prefix(self) -> str:
        return _service_wire_prefix(self.name)


class ProtoFile:
    def __init__(self, package: str, services: List[ProtoService]):
        self.package = package
        self.services = services


def parse_proto(proto_path: Path) -> ProtoFile:
    text = _strip_comments(proto_path.read_text(encoding='utf-8'))

    pkg_match = re.search(r'\bpackage\s+([\w.]+)\s*;', text)
    package = pkg_match.group(1) if pkg_match else ''

    services: List[ProtoService] = []
    for svc_match in re.finditer(r'\bservice\s+(\w+)\s*\{([^}]*)\}', text, re.DOTALL):
        svc_name = svc_match.group(1)
        svc_body = svc_match.group(2)

        rpcs: List[ProtoRpc] = []
        for rpc_match in re.finditer(
                r'\brpc\s+(\w+)\s*\(\s*([\w.]+)\s*\)\s*returns\s*\(\s*(stream\s+)?([\w.]+)\s*\)',
                svc_body):
            rpc_name = rpc_match.group(1)
            req_type = rpc_match.group(2)
            streaming = bool(rpc_match.group(3))
            rsp_type = rpc_match.group(4)
            rpcs.append(ProtoRpc(rpc_name, req_type, rsp_type, streaming))

        services.append(ProtoService(svc_name, rpcs))

    return ProtoFile(package, services)


# -- Ada package name derivation -----------------------------------------------

def _pkg_name_from_proto(proto_file: ProtoFile) -> str:
    parts = proto_file.package.split('.')

    last = parts[-1].lower()
    explicit_suffix = None
    if last in ('provided', 'consumed'):
        explicit_suffix = parts[-1].capitalize()
        parts = parts[:-1]

    skip = {'pyramid', 'components', 'data_model', 'base', 'services'}
    meaningful = [p for p in parts if p.lower() not in skip]

    ada_parts = ['Pyramid', 'Services']
    for p in meaningful:
        titled = '_'.join(w.capitalize() for w in p.split('_'))
        ada_parts.append(titled)

    ada_parts.append(explicit_suffix if explicit_suffix else 'Provided')
    return '.'.join(ada_parts)


def _is_provided(proto_file: ProtoFile) -> bool:
    return 'provided' in proto_file.package.lower()


_DATA_MODEL_TYPES_PKG = 'Pyramid_Data_Model_Types'

def _types_pkg_from_proto(proto_file: ProtoFile) -> str:
    """Return the Ada types package name for the data model.

    All services reference the shared data model types package regardless
    of which service proto is being generated.
    """
    return _DATA_MODEL_TYPES_PKG


def _codec_pkg_from_proto(proto_file: ProtoFile) -> str:
    """Derive Ada JSON codec package name from proto package.

    pyramid.components.tactical_objects.services.provided
      -> Pyramid.Services.Tactical_Objects.Json_Codec
    """
    parts = proto_file.package.split('.')
    if parts and parts[-1].lower() in ('provided', 'consumed'):
        parts = parts[:-1]
    skip = {'pyramid', 'components', 'data_model', 'base', 'services'}
    meaningful = [p for p in parts if p.lower() not in skip]
    ada_parts = ['Pyramid', 'Services']
    for p in meaningful:
        ada_parts.append('_'.join(w.capitalize() for w in p.split('_')))
    ada_parts.append('Json_Codec')
    return '.'.join(ada_parts)


# -- Code generation -----------------------------------------------------------

class AdaServiceGenerator:

    def __init__(self, proto_input: str):
        self._proto_input = Path(proto_input)

    def generate(self, output_dir: str):
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        proto_files: List[Path] = []
        if self._proto_input.is_dir():
            proto_files = list(self._proto_input.rglob('*.proto'))
        elif self._proto_input.is_file():
            proto_files = [self._proto_input]
        else:
            print(f'ERROR: {self._proto_input} is not a file or directory', file=sys.stderr)
            sys.exit(1)

        for pf in proto_files:
            parsed = parse_proto(pf)
            all_rpcs: List[Tuple[str, ProtoRpc]] = []
            for svc in parsed.services:
                for rpc in svc.rpcs:
                    all_rpcs.append((svc.name, rpc))

            if not all_rpcs:
                continue

            pkg_name = _pkg_name_from_proto(parsed)
            ads_path = output_path / (pkg_name.lower().replace('.', '-') + '.ads')
            adb_path = output_path / (pkg_name.lower().replace('.', '-') + '.adb')

            self._write_spec(ads_path, pkg_name, parsed, all_rpcs)
            self._write_body(adb_path, pkg_name, parsed, all_rpcs)
            print(f'  Generated {pkg_name}')

    # -- Spec (.ads) -----------------------------------------------------------

    def _write_spec(self, path: Path, pkg_name: str, parsed: ProtoFile,
                    all_rpcs: List[Tuple[str, ProtoRpc]]):
        entity_types_for_arrays = sorted({
            _proto_type_to_ada(_short_type(rpc.rsp))
            for _, rpc in all_rpcs if rpc.streaming
        })

        is_provided = _is_provided(parsed)
        # Provided bindings: Ada client subscribes to server-published topics
        # Consumed bindings: Ada client publishes to server-subscribed topics
        sub_topics  = SUBSCRIBE_TOPICS if is_provided else {}
        pub_topics  = {} if is_provided else PUBLISH_TOPICS

        with open(path, 'w') as f:
            f.write(f'--  Auto-generated service binding specification\n')
            f.write(f'--  Generated from: {self._proto_input.name}'
                    f' by ada_service_generator.py\n')
            f.write(f'--  Package: {pkg_name}\n')
            f.write(f'--\n')
            f.write(f'--  Architecture: component logic > service binding (this) > PCL\n')
            f.write(f'--\n')
            f.write(f'--  This package provides:\n')
            f.write(f'--    1. Wire-name constants and topic constants\n')
            f.write(f'--    2. EntityActions handler stubs (Handle_*)\n')
            f.write(f'--    3. PCL binding procedures (Subscribe_*, Invoke_*, Publish_*)\n')
            f.write(f'--    4. Msg_To_String utility for PCL message payloads\n')
            f.write(f'--\n')
            codec_pkg = _codec_pkg_from_proto(parsed)
            types_pkg = _types_pkg_from_proto(parsed)
            f.write(f'--  JSON serialisation/deserialisation is provided by the companion\n')
            f.write(f'--  {codec_pkg} package.\n')
            f.write(f'\n')
            f.write(f'with {types_pkg};  use {types_pkg};\n')
            f.write(f'with Pcl_Bindings;\n')
            f.write(f'with Interfaces.C;\n')
            f.write(f'with System;\n')
            f.write(f'\n')
            f.write(f'package {pkg_name} is\n')
            f.write(f'\n')

            # Operation_Kind enumeration
            f.write(f'   type Operation_Kind is\n')
            f.write(f'     (Op_Create,\n')
            f.write(f'      Op_Read,\n')
            f.write(f'      Op_Update,\n')
            f.write(f'      Op_Delete);\n')
            f.write(f'\n')

            # Service_Channel enumeration
            f.write(f'   type Service_Channel is\n')
            channel_values = [f'      {rpc.ada_channel}' for _, rpc in all_rpcs]
            if channel_values:
                f.write('     (' + ',\n'.join(channel_values).lstrip() + ');\n')
            else:
                f.write('     (Ch_None);\n')
            f.write('\n')

            # Array types for streaming Read responses
            for et in entity_types_for_arrays:
                f.write(f'   type {et}_Array is array (Positive range <>) of {et};\n')
            if entity_types_for_arrays:
                f.write('\n')

            # -- Service wire-name constants -----------------------------------
            f.write(f'   --  -- Service wire-name constants (generated from proto) --------\n')
            f.write(f'\n')

            for svc in parsed.services:
                prefix = svc.wire_prefix
                for rpc in svc.rpcs:
                    const_name = f'Svc_{_camel_to_snake(rpc.name)}'
                    wire_name = f'{prefix}.{rpc.wire_name}'
                    f.write(f'   {const_name} : constant String :=\n')
                    f.write(f'     "{wire_name}";\n')
            f.write('\n')

            # -- Topic name constants ------------------------------------------
            all_topics = dict(sub_topics)
            all_topics.update(pub_topics)
            if all_topics:
                f.write(f'   --  -- Standard topic name constants --------------------------\n')
                f.write(f'\n')
                for key, wire in all_topics.items():
                    const_name = 'Topic_' + '_'.join(
                        w.capitalize() for w in key.split('_'))
                    f.write(f'   {const_name} : constant String :=\n')
                    f.write(f'     "{wire}";\n')
                f.write('\n')

            # -- Msg_To_String utility -----------------------------------------
            f.write(f'   --  -- PCL message utility ------------------------------------\n')
            f.write(f'\n')
            f.write(f'   function Msg_To_String\n')
            f.write(f'     (Data : System.Address;\n')
            f.write(f'      Size : Interfaces.C.unsigned) return String;\n')
            f.write(f'\n')

            # Handler procedure declarations
            f.write(f'   --  -- EntityActions handlers ------------------------------------\n')
            f.write(f'   --  Implement these procedures in the package body.\n')
            f.write(f'\n')

            current_svc = None
            for svc_name, rpc in all_rpcs:
                if svc_name != current_svc:
                    f.write(f'   --  {svc_name}\n')
                    current_svc = svc_name

                req_t = rpc.ada_req_type
                rsp_t = rpc.ada_rsp_type

                f.write(f'   procedure {rpc.ada_handler}\n')
                f.write(f'     (Request  : in  {req_t};\n')
                f.write(f'      Response : out {rsp_t});\n')

            f.write('\n')

            # -- PCL binding procedures ----------------------------------------
            f.write(f'   --  -- PCL binding procedures ------------------------------------\n')
            f.write(f'   --  Subscribe/Invoke/Publish wrappers for PCL transport layer.\n')
            f.write(f'   --  Use Json_Codec to serialise/deserialise message payloads.\n')
            f.write(f'\n')

            # Subscribe helpers for topics (provided side: Ada client subscribes)
            for key in sub_topics:
                ada_name = 'Subscribe_' + '_'.join(
                    w.capitalize() for w in key.split('_'))
                f.write(f'   procedure {ada_name}\n')
                f.write(f'     (Container : Pcl_Bindings.Pcl_Container_Access;\n')
                f.write(f'      Callback  : Pcl_Bindings.Pcl_Sub_Callback_Access;\n')
                f.write(f'      User_Data : System.Address := System.Null_Address);\n')
                f.write(f'\n')

            # Invoke helpers for services (provided = client can call them)
            if is_provided:
                for svc in parsed.services:
                    for rpc in svc.rpcs:
                        f.write(f'   procedure {rpc.ada_invoke_name}\n')
                        f.write(f'     (Transport : Pcl_Bindings.Pcl_Socket_Transport_Access;\n')
                        f.write(f'      Request   : String;\n')
                        f.write(f'      Callback  : Pcl_Bindings.Pcl_Resp_Cb_Access;\n')
                        f.write(f'      User_Data : System.Address := System.Null_Address);\n')
                        f.write(f'\n')

            # Publish helpers for consumed topics (Ada client publishes to server)
            for key in pub_topics:
                ada_name = 'Publish_' + '_'.join(
                    w.capitalize() for w in key.split('_'))
                f.write(f'   procedure {ada_name}\n')
                f.write(f'     (Exec    : Pcl_Bindings.Pcl_Executor_Access;\n')
                f.write(f'      Payload : String);\n')
                f.write(f'\n')

            # Dispatch procedure
            f.write(f'   --  -- Transport integration point ------------------------------\n')
            f.write(f'\n')
            f.write(f'   procedure Dispatch\n')
            f.write(f'     (Channel      : in  Service_Channel;\n')
            f.write(f'      Request_Buf  : in  System.Address;\n')
            f.write(f'      Request_Size : in  Natural;\n')
            f.write(f'      Response_Buf : out System.Address;\n')
            f.write(f'      Response_Size: out Natural);\n')
            f.write(f'\n')
            f.write(f'end {pkg_name};\n')

    # -- Body (.adb) -----------------------------------------------------------

    def _write_body(self, path: Path, pkg_name: str, parsed: ProtoFile,
                    all_rpcs: List[Tuple[str, ProtoRpc]]):
        is_provided = _is_provided(parsed)
        sub_topics  = SUBSCRIBE_TOPICS if is_provided else {}
        pub_topics  = {} if is_provided else PUBLISH_TOPICS

        with open(path, 'w') as f:
            f.write(f'--  Auto-generated service binding body\n')
            f.write(f'--  Package body: {pkg_name}\n')
            f.write(f'\n')
            f.write(f'with Ada.Unchecked_Conversion;\n')
            f.write(f'with Interfaces.C.Strings;\n')
            f.write(f'with System;\n')
            f.write(f'with System.Storage_Elements;\n')
            f.write(f'\n')
            f.write(f'package body {pkg_name} is\n')
            f.write(f'\n')

            # -- Internal helpers ----------------------------------------------
            f.write(f'   function To_Address is new\n')
            f.write(f'     Ada.Unchecked_Conversion (Interfaces.C.Strings.chars_ptr, System.Address);\n')
            f.write(f'\n')

            # -- Msg_To_String -------------------------------------------------
            f.write(f'   function Msg_To_String\n')
            f.write(f'     (Data : System.Address;\n')
            f.write(f'      Size : Interfaces.C.unsigned) return String\n')
            f.write(f'   is\n')
            f.write(f'      use System.Storage_Elements;\n')
            f.write(f'      type Char_Array is array (1 .. Natural (Size)) of Character;\n')
            f.write(f'      pragma Pack (Char_Array);\n')
            f.write(f'      Chars : Char_Array;\n')
            f.write(f"      for Chars'Address use Data;\n")
            f.write(f'      pragma Import (Ada, Chars);\n')
            f.write(f'   begin\n')
            f.write(f'      return String (Chars);\n')
            f.write(f'   end Msg_To_String;\n')
            f.write(f'\n')

            # Handler stubs
            current_svc = None
            for svc_name, rpc in all_rpcs:
                if svc_name != current_svc:
                    f.write(f'   --  -- {svc_name} ------------------------------------\n')
                    current_svc = svc_name

                req_t = rpc.ada_req_type
                rsp_t = rpc.ada_rsp_type

                f.write(f'   procedure {rpc.ada_handler}\n')
                f.write(f'     (Request  : in  {req_t};\n')
                f.write(f'      Response : out {rsp_t})\n')
                f.write(f'   is\n')
                f.write(f'      pragma Unreferenced (Request);\n')

                # Generate sensible default return values
                if rsp_t == 'Identifier':
                    f.write(f'   begin\n')
                    f.write(f'      Response := Null_Identifier;\n')
                elif rsp_t == 'Ack':
                    f.write(f'   begin\n')
                    f.write(f'      Response := Ack_Ok;\n')
                elif rsp_t.endswith('_Array'):
                    f.write(f'      Empty : {rsp_t} (1 .. 0);\n')
                    f.write(f'   begin\n')
                    f.write(f'      Response := Empty;\n')
                else:
                    f.write(f'      Default_Val : {rsp_t};\n')
                    f.write(f'   begin\n')
                    f.write(f'      Response := Default_Val;\n')

                f.write(f'   end {rpc.ada_handler};\n')
                f.write(f'\n')

            # -- PCL binding implementations -----------------------------------
            f.write(f'   --  -- PCL binding implementations -------------------------------\n')
            f.write(f'\n')

            # Subscribe helpers (provided side)
            for key, wire in sub_topics.items():
                ada_name = 'Subscribe_' + '_'.join(
                    w.capitalize() for w in key.split('_'))
                const_name = 'Topic_' + '_'.join(
                    w.capitalize() for w in key.split('_'))

                f.write(f'   procedure {ada_name}\n')
                f.write(f'     (Container : Pcl_Bindings.Pcl_Container_Access;\n')
                f.write(f'      Callback  : Pcl_Bindings.Pcl_Sub_Callback_Access;\n')
                f.write(f'      User_Data : System.Address := System.Null_Address)\n')
                f.write(f'   is\n')
                f.write(f'      Topic  : Interfaces.C.Strings.chars_ptr :=\n')
                f.write(f'        Interfaces.C.Strings.New_String ({const_name});\n')
                f.write(f'      Type_N : Interfaces.C.Strings.chars_ptr :=\n')
                f.write(f'        Interfaces.C.Strings.New_String ("application/json");\n')
                f.write(f'      Port   : Pcl_Bindings.Pcl_Port_Access;\n')
                f.write(f'      pragma Unreferenced (Port);\n')
                f.write(f'   begin\n')
                f.write(f'      Port := Pcl_Bindings.Add_Subscriber\n')
                f.write(f'        (Container => Container,\n')
                f.write(f'         Topic     => Topic,\n')
                f.write(f'         Type_Name => Type_N,\n')
                f.write(f'         Callback  => Callback,\n')
                f.write(f'         User_Data => User_Data);\n')
                f.write(f'      Interfaces.C.Strings.Free (Topic);\n')
                f.write(f'      Interfaces.C.Strings.Free (Type_N);\n')
                f.write(f'   end {ada_name};\n')
                f.write(f'\n')

            # Invoke helpers (provided services)
            if is_provided:
                for svc in parsed.services:
                    for rpc in svc.rpcs:
                        f.write(f'   procedure {rpc.ada_invoke_name}\n')
                        f.write(f'     (Transport : Pcl_Bindings.Pcl_Socket_Transport_Access;\n')
                        f.write(f'      Request   : String;\n')
                        f.write(f'      Callback  : Pcl_Bindings.Pcl_Resp_Cb_Access;\n')
                        f.write(f'      User_Data : System.Address := System.Null_Address)\n')
                        f.write(f'   is\n')
                        f.write(f'      use type Pcl_Bindings.Pcl_Status;\n')
                        f.write(f'      Req_C  : Interfaces.C.Strings.chars_ptr :=\n')
                        f.write(f'        Interfaces.C.Strings.New_String (Request);\n')
                        f.write(f'      Svc_C  : Interfaces.C.Strings.chars_ptr :=\n')
                        f.write(f'        Interfaces.C.Strings.New_String ({rpc.ada_svc_const});\n')
                        f.write(f'      Msg    : aliased Pcl_Bindings.Pcl_Msg;\n')
                        f.write(f'      Status : Pcl_Bindings.Pcl_Status;\n')
                        f.write(f'      pragma Unreferenced (Status);\n')
                        f.write(f'   begin\n')
                        f.write(f"      Msg.Data      := To_Address (Req_C);\n")
                        f.write(f"      Msg.Size      := Interfaces.C.unsigned (Request'Length);\n")
                        f.write(f'      Msg.Type_Name := Interfaces.C.Strings.New_String ("application/json");\n')
                        f.write(f'      Status := Pcl_Bindings.Invoke_Remote_Async\n')
                        f.write(f"        (Transport, Svc_C, Msg'Access, Callback, User_Data);\n")
                        f.write(f'      Interfaces.C.Strings.Free (Req_C);\n')
                        f.write(f'      Interfaces.C.Strings.Free (Svc_C);\n')
                        f.write(f'      Interfaces.C.Strings.Free (Msg.Type_Name);\n')
                        f.write(f'   end {rpc.ada_invoke_name};\n')
                        f.write(f'\n')

            # Publish helpers (consumed topics — Ada client publishes to server)
            for key, wire in pub_topics.items():
                ada_name = 'Publish_' + '_'.join(
                    w.capitalize() for w in key.split('_'))
                const_name = 'Topic_' + '_'.join(
                    w.capitalize() for w in key.split('_'))

                f.write(f'   procedure {ada_name}\n')
                f.write(f'     (Exec    : Pcl_Bindings.Pcl_Executor_Access;\n')
                f.write(f'      Payload : String)\n')
                f.write(f'   is\n')
                f.write(f'      use type Pcl_Bindings.Pcl_Status;\n')
                f.write(f'      Payload_C : Interfaces.C.Strings.chars_ptr :=\n')
                f.write(f'        Interfaces.C.Strings.New_String (Payload);\n')
                f.write(f'      Topic_C   : Interfaces.C.Strings.chars_ptr :=\n')
                f.write(f'        Interfaces.C.Strings.New_String ({const_name});\n')
                f.write(f'      Msg       : aliased Pcl_Bindings.Pcl_Msg;\n')
                f.write(f'      Status    : Pcl_Bindings.Pcl_Status;\n')
                f.write(f'      pragma Unreferenced (Status);\n')
                f.write(f'   begin\n')
                f.write(f"      Msg.Data      := To_Address (Payload_C);\n")
                f.write(f"      Msg.Size      := Interfaces.C.unsigned (Payload'Length);\n")
                f.write(f'      Msg.Type_Name := Interfaces.C.Strings.New_String ("application/json");\n')
                f.write(f"      Status := Pcl_Bindings.Publish (Exec, Topic_C, Msg'Access);\n")
                f.write(f'      Interfaces.C.Strings.Free (Payload_C);\n')
                f.write(f'      Interfaces.C.Strings.Free (Topic_C);\n')
                f.write(f'      Interfaces.C.Strings.Free (Msg.Type_Name);\n')
                f.write(f'   end {ada_name};\n')
                f.write(f'\n')

            # Dispatch stub with case statement
            f.write(f'   procedure Dispatch\n')
            f.write(f'     (Channel      : in  Service_Channel;\n')
            f.write(f'      Request_Buf  : in  System.Address;\n')
            f.write(f'      Request_Size : in  Natural;\n')
            f.write(f'      Response_Buf : out System.Address;\n')
            f.write(f'      Response_Size: out Natural)\n')
            f.write(f'   is\n')
            f.write(f'      pragma Unreferenced (Request_Buf, Request_Size);\n')
            f.write(f'   begin\n')
            f.write(f'      Response_Buf  := System.Null_Address;\n')
            f.write(f'      Response_Size := 0;\n')
            f.write(f'      case Channel is\n')

            for _, rpc in all_rpcs:
                f.write(f'         when {rpc.ada_channel} =>\n')
                f.write(f'            null;  --  TODO: deserialise, call {rpc.ada_handler}\n')

            f.write(f'      end case;\n')
            f.write(f'   end Dispatch;\n')
            f.write(f'\n')
            f.write(f'end {pkg_name};\n')


# -- JSON Codec Generator -----------------------------------------------------


def _ada_tag(key: str) -> str:
    """entity_matches -> Entity_Matches."""
    return '_'.join(w.capitalize() for w in key.split('_'))


class JsonCodecGenerator:
    """Generates the canonical JSON ser/de package from json_schema.py.

    Output package name is derived from the supplied .proto file.
    This package provides typed To_Json / From_Json for every message defined
    in json_schema.ALL_SCHEMAS, plus enum-to-string converters.

    Usage:
        gen = JsonCodecGenerator(proto_file)
        gen.generate('/path/to/output_dir')
    """

    def __init__(self, proto_file: ProtoFile):
        self.PKG = _codec_pkg_from_proto(proto_file)
        self._types_pkg = _types_pkg_from_proto(proto_file)

    def generate(self, output_dir: str):
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        ads = out / (self.PKG.lower().replace('.', '-') + '.ads')
        adb = out / (self.PKG.lower().replace('.', '-') + '.adb')
        self._write_spec(ads)
        self._write_body(adb)
        print(f'  Generated {self.PKG}')

    # -- Spec ------------------------------------------------------------------

    def _write_spec(self, path: Path):
        ek = schema.FieldKind

        with open(path, 'w') as f:
            f.write('--  Auto-generated JSON codec specification\n')
            f.write(f'--  Package: {self.PKG}\n')
            f.write('--  Generated by ada_service_generator.py (JsonCodecGenerator)\n')
            f.write('--  Schema source: pim/json_schema.py\n')
            f.write('--\n')
            f.write('--  Canonical JSON wire format for the pyramid standard bridge protocol.\n')
            f.write('--  Each message schema maps directly to a proto message type:\n')
            f.write('--\n')
            for msg in schema.ALL_SCHEMAS:
                f.write(f'--    {msg.ada_name:<34} {msg.wire_description}\n')
            f.write('--\n')
            f.write('--  Architecture: component logic > Json_Codec > service binding > PCL\n')
            f.write('\n')
            f.write('with Ada.Strings.Unbounded;  use Ada.Strings.Unbounded;\n')
            f.write(f'with {self._types_pkg};  use {self._types_pkg};\n')
            f.write('\n')
            f.write(f'package {self.PKG} is\n')
            f.write('\n')

            # -- Record type declarations --------------------------------------
            for msg in schema.ALL_SCHEMAS:
                f.write(f'   --  -- {msg.ada_name} {"─" * max(1, 60 - len(msg.ada_name))}\n')
                f.write(f'   --  {msg.wire_description}\n')
                f.write(f'   type {msg.ada_name} is record\n')
                for fld in msg.fields:
                    comment = f'  --  {fld.description}' if fld.description else ''
                    req_tag = '' if fld.required else '  --  optional'
                    tag = comment or req_tag
                    f.write(f'      {fld.ada_field_name:<24}: {fld.ada_type} := {fld.ada_default};{tag}\n')
                f.write(f'   end record;\n')
                f.write(f'\n')

            # Array type for entity matches
            f.write('   type Entity_Match_Array is\n')
            f.write('     array (Positive range <>) of Entity_Match;\n')
            f.write('\n')

            # -- Serialisation functions ---------------------------------------
            f.write('   --  -- Serialisation (To_Json) -----------------------------------------\n')
            f.write('\n')
            for msg in schema.ALL_SCHEMAS:
                f.write(f'   function To_Json (Msg : {msg.ada_name}) return String;\n')
            f.write('\n')

            # -- Deserialisation functions -------------------------------------
            f.write('   --  -- Deserialisation (From_Json) ------------------------------------\n')
            f.write('\n')
            for msg in schema.ALL_SCHEMAS:
                f.write(f'   function From_Json\n')
                f.write(f'     (S : String) return {msg.ada_name};\n')
            f.write('\n')

            # Array deserialiser for entity_matches
            f.write('   --  Deserialise standard.entity_matches JSON array\n')
            f.write('   function Entity_Matches_From_Json\n')
            f.write('     (S : String) return Entity_Match_Array;\n')
            f.write('\n')

            # -- Enum string converters ----------------------------------------
            f.write('   --  -- Enum string converters -----------------------------------------\n')
            f.write('\n')
            for _kind, spec in schema.ENUM_SPECS.items():
                f.write(f'   function {spec.ada_to_str_fn} (V : {spec.ada_type}) return String;\n')
                f.write(f'   function {spec.ada_from_str_fn} (S : String) return {spec.ada_type};\n')
            f.write('\n')

            f.write(f'end {self.PKG};\n')

    # -- Body ------------------------------------------------------------------

    def _write_body(self, path: Path):
        ek = schema.FieldKind

        with open(path, 'w') as f:
            f.write('--  Auto-generated JSON codec body\n')
            f.write(f'--  Package body: {self.PKG}\n')
            f.write('\n')
            f.write('with GNATCOLL.JSON;  use GNATCOLL.JSON;\n')
            f.write('\n')
            f.write(f'package body {self.PKG} is\n')
            f.write('\n')

            # -- Internal float helpers ----------------------------------------
            f.write('   --  -- Internal helpers -------------------------------------------\n')
            f.write('\n')
            f.write('   procedure Set_F\n')
            f.write('     (Obj  : in out JSON_Value;\n')
            f.write('      Name : String;\n')
            f.write('      Val  : Long_Float)\n')
            f.write('   is\n')
            f.write('   begin\n')
            f.write('      Set_Field (Obj, Name, JSON_Float (Val));\n')
            f.write('   end Set_F;\n')
            f.write('\n')
            f.write('   function Get_F\n')
            f.write('     (J    : JSON_Value;\n')
            f.write('      Name : String;\n')
            f.write('      Def  : Long_Float := 0.0) return Long_Float\n')
            f.write('   is\n')
            f.write('   begin\n')
            f.write('      if Has_Field (J, Name) then\n')
            f.write('         return Long_Float (JSON_Float\'(Get (Get (J, Name))));\n')
            f.write('      end if;\n')
            f.write('      return Def;\n')
            f.write('   exception\n')
            f.write('      when others => return Def;\n')
            f.write('   end Get_F;\n')
            f.write('\n')
            f.write('   function Get_S\n')
            f.write('     (J    : JSON_Value;\n')
            f.write('      Name : String;\n')
            f.write('      Def  : String := "") return String\n')
            f.write('   is\n')
            f.write('   begin\n')
            f.write('      if Has_Field (J, Name) then\n')
            f.write('         return Get (Get (J, Name));\n')
            f.write('      end if;\n')
            f.write('      return Def;\n')
            f.write('   exception\n')
            f.write('      when others => return Def;\n')
            f.write('   end Get_S;\n')
            f.write('\n')

            # -- Enum string converters ----------------------------------------
            f.write('   --  -- Enum string converters -----------------------------------------\n')
            f.write('\n')
            for _kind, spec in schema.ENUM_SPECS.items():
                table = spec.table()

                # To_String
                f.write(f'   function {spec.ada_to_str_fn} (V : {spec.ada_type}) return String is\n')
                f.write(f'   begin\n')
                f.write(f'      case V is\n')
                for proto_str, ada_lit, _cpp_lit, _ord in table:
                    f.write(f'         when {ada_lit} => return "{proto_str}";\n')
                f.write(f'      end case;\n')
                f.write(f'   end {spec.ada_to_str_fn};\n')
                f.write('\n')

                # From_String
                f.write(f'   function {spec.ada_from_str_fn} (S : String) return {spec.ada_type} is\n')
                f.write(f'   begin\n')
                for proto_str, ada_lit, _cpp_lit, _ord in table:
                    f.write(f'      if S = "{proto_str}" then return {ada_lit}; end if;\n')
                f.write(f'      return {spec.default_ada};\n')
                f.write(f'   end {spec.ada_from_str_fn};\n')
                f.write('\n')

            # -- To_Json implementations --------------------------------------
            f.write('   --  -- To_Json ------------------------------------------------------\n')
            f.write('\n')
            for msg in schema.ALL_SCHEMAS:
                f.write(f'   function To_Json (Msg : {msg.ada_name}) return String is\n')
                f.write(f'      Obj : JSON_Value := Create_Object;\n')
                f.write(f'   begin\n')
                for fld in msg.fields:
                    fname = fld.ada_field_name
                    jkey  = fld.name
                    if fld.kind == ek.DOUBLE:
                        if fld.required:
                            f.write(f'      Set_F (Obj, "{jkey}", Msg.{fname});\n')
                        else:
                            f.write(f'      if Msg.{fname} /= 0.0 then\n')
                            f.write(f'         Set_F (Obj, "{jkey}", Msg.{fname});\n')
                            f.write(f'      end if;\n')
                    elif fld.kind == ek.BOOL:
                        f.write(f'      Set_Field (Obj, "{jkey}", Msg.{fname});\n')
                    elif fld.kind in (ek.STRING, ek.IDENTIFIER):
                        if fld.required:
                            f.write(f'      Set_Field (Obj, "{jkey}", To_String (Msg.{fname}));\n')
                        else:
                            f.write(f'      if Msg.{fname} /= Null_Unbounded_String then\n')
                            f.write(f'         Set_Field (Obj, "{jkey}", To_String (Msg.{fname}));\n')
                            f.write(f'      end if;\n')
                    elif fld.is_enum:
                        spec = schema.ENUM_SPECS[fld.kind]
                        if fld.required:
                            f.write(f'      Set_Field (Obj, "{jkey}", {spec.ada_to_str_fn} (Msg.{fname}));\n')
                        else:
                            f.write(f'      if Msg.{fname} /= {spec.default_ada} then\n')
                            f.write(f'         Set_Field (Obj, "{jkey}", {spec.ada_to_str_fn} (Msg.{fname}));\n')
                            f.write(f'      end if;\n')
                f.write(f'      return Write (Obj);\n')
                f.write(f'   end To_Json;\n')
                f.write('\n')

            # -- From_Json implementations ------------------------------------
            f.write('   --  -- From_Json ----------------------------------------------------\n')
            f.write('\n')
            for msg in schema.ALL_SCHEMAS:
                f.write(f'   function From_Json\n')
                f.write(f'     (S : String) return {msg.ada_name}\n')
                f.write(f'   is\n')
                f.write(f'      Result : {msg.ada_name};\n')
                f.write(f'      J      : JSON_Value;\n')
                f.write(f'      R      : Read_Result;\n')
                f.write(f'   begin\n')
                f.write(f'      R := Read (S);\n')
                f.write(f'      if not R.Success or else R.Value.Kind /= JSON_Object_Type then\n')
                f.write(f'         return Result;\n')
                f.write(f'      end if;\n')
                f.write(f'      J := R.Value;\n')
                for fld in msg.fields:
                    fname = fld.ada_field_name
                    jkey  = fld.name
                    if fld.kind == ek.DOUBLE:
                        f.write(f'      Result.{fname} := Get_F (J, "{jkey}");\n')
                    elif fld.kind == ek.BOOL:
                        f.write(f'      if Has_Field (J, "{jkey}") then\n')
                        f.write(f'         Result.{fname} := Boolean\'(Get (Get (J, "{jkey}")));\n')
                        f.write(f'      end if;\n')
                    elif fld.kind in (ek.STRING, ek.IDENTIFIER):
                        f.write(f'      Result.{fname} :=\n')
                        f.write(f'        To_Unbounded_String (Get_S (J, "{jkey}"));\n')
                    elif fld.is_enum:
                        spec = schema.ENUM_SPECS[fld.kind]
                        f.write(f'      Result.{fname} :=\n')
                        f.write(f'        {spec.ada_from_str_fn} (Get_S (J, "{jkey}"));\n')
                f.write(f'      return Result;\n')
                f.write(f'   end From_Json;\n')
                f.write('\n')

            # -- Entity_Matches_From_Json --------------------------------------
            f.write('   --  -- Entity_Matches_From_Json ------------------------------------\n')
            f.write('\n')
            f.write('   function Entity_Matches_From_Json\n')
            f.write('     (S : String) return Entity_Match_Array\n')
            f.write('   is\n')
            f.write('      R   : Read_Result;\n')
            f.write('      Arr : JSON_Array;\n')
            f.write('   begin\n')
            f.write('      R := Read (S);\n')
            f.write('      if not R.Success or else R.Value.Kind /= JSON_Array_Type then\n')
            f.write('         return (1 .. 0 => <>);\n')
            f.write('      end if;\n')
            f.write('      Arr := Get (R.Value);\n')
            f.write('      declare\n')
            f.write('         Result : Entity_Match_Array (1 .. Length (Arr));\n')
            f.write('      begin\n')
            f.write('         for I in 1 .. Length (Arr) loop\n')
            f.write('            declare\n')
            f.write('               Elem : constant JSON_Value := Get (Arr, I);\n')
            f.write('               M    : Entity_Match;\n')
            f.write('            begin\n')
            for fld in schema.ENTITY_MATCH.fields:
                fname = fld.ada_field_name
                jkey  = fld.name
                if fld.kind == ek.DOUBLE:
                    f.write(f'               M.{fname} := Get_F (Elem, "{jkey}");\n')
                elif fld.kind in (ek.STRING, ek.IDENTIFIER):
                    f.write(f'               M.{fname} :=\n')
                    f.write(f'                 To_Unbounded_String (Get_S (Elem, "{jkey}"));\n')
                elif fld.is_enum:
                    spec = schema.ENUM_SPECS[fld.kind]
                    f.write(f'               M.{fname} :=\n')
                    f.write(f'                 {spec.ada_from_str_fn} (Get_S (Elem, "{jkey}"));\n')
            f.write('               Result (I) := M;\n')
            f.write('            end;\n')
            f.write('         end loop;\n')
            f.write('         return Result;\n')
            f.write('      end;\n')
            f.write('   end Entity_Matches_From_Json;\n')
            f.write('\n')

            f.write(f'end {self.PKG};\n')


# ---------------------------------------------------------------------------
# Ada types package generator
# ---------------------------------------------------------------------------

_ADA_SCALAR_MAP: Dict[str, str] = {
    'double': 'Long_Float', 'float': 'Float',
    'int32': 'Integer', 'int64': 'Long_Integer',
    'uint32': 'Natural', 'uint64': 'Long_Integer',
    'sint32': 'Integer', 'sint64': 'Long_Integer',
    'fixed32': 'Natural', 'fixed64': 'Long_Integer',
    'sfixed32': 'Integer', 'sfixed64': 'Long_Integer',
    'bool': 'Boolean', 'string': 'Unbounded_String', 'bytes': 'Unbounded_String',
}

_ADA_DEFAULTS: Dict[str, str] = {
    'Long_Float': '0.0', 'Float': '0.0',
    'Integer': '0', 'Long_Integer': '0', 'Natural': '0',
    'Boolean': 'False', 'Unbounded_String': 'Null_Unbounded_String',
}

_ADA_UNIT_FIELD_NAMES = frozenset({
    'value', 'radians', 'meters', 'meters_per_second', 'seconds',
})


def _ada_name(cpp_or_proto_name: str) -> str:
    """Convert CamelCase or snake_case proto name to Ada Title_Case."""
    s = camel_to_snake(cpp_or_proto_name)   # CamelCase → Camel_Case
    return '_'.join(w.capitalize() for w in s.split('_'))


def _common_ada_pkg(index: ProtoTypeIndex) -> str:
    """Derive Ada package name from common package prefix of data model protos.

    e.g. pyramid.data_model.base, pyramid.data_model.common
      -> Pyramid_Data_Model_Types
    """
    pkgs = [pf.package for pf in index.files if pf.package]
    if not pkgs:
        return 'Data_Model_Types'
    parts = [p.split('.') for p in pkgs]
    common = parts[0]
    for p in parts[1:]:
        common = [a for a, b in zip(common, p) if a == b]
    ada_parts = ['_'.join(w.capitalize() for w in seg.split('_')) for seg in common]
    return '_'.join(ada_parts) + '_Types'


class AdaTypesGenerator:
    """Generates ``{Prefix}_Types.ads`` from data model proto files.

    Scalar wrapper messages are emitted as subtypes; all other messages become
    record types.  Enums are emitted with a ``{Last_Word}_`` prefix on each
    literal.

    The Ada package name and output file name are derived automatically from
    the common package prefix of the data model proto files.

    Usage::
        gen = AdaTypesGenerator(data_model_dir)
        gen.generate(output_dir)
    """

    def __init__(self, data_model_dir: Path):
        proto_files = parse_proto_tree(data_model_dir)
        self._index = ProtoTypeIndex(proto_files)
        self._data_model_dir = data_model_dir
        self._ada_pkg = _common_ada_pkg(self._index)
        self._file_base = self._ada_pkg.lower().replace('.', '-')
        self._aliases = self._find_scalar_wrappers()

    # -- public ----------------------------------------------------------------

    def generate(self, output_dir: str) -> None:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        ads = out / (self._file_base + '.ads')
        self._write_ads(ads)
        print(f'  Generated {self._ada_pkg}')

    # -- internal --------------------------------------------------------------

    def _find_scalar_wrappers(self) -> Dict[str, str]:
        aliases: Dict[str, str] = {'Timestamp': 'Long_Float'}
        for msg in self._index.all_messages():
            fields = msg.all_fields()
            if len(fields) == 1 and not fields[0].is_repeated:
                ft = fields[0].type
                fn = fields[0].name
                if ft in _ADA_SCALAR_MAP and fn in _ADA_UNIT_FIELD_NAMES:
                    aliases[msg.name] = _ADA_SCALAR_MAP[ft]
        return aliases

    def _ada_base_type(self, field_type: str) -> str:
        """Resolve a proto type to its Ada element type name."""
        short = field_type.split('.')[-1]
        if field_type in _ADA_SCALAR_MAP:
            return _ADA_SCALAR_MAP[field_type]
        if short in self._aliases:
            return self._aliases[short]
        if self._index.is_enum_type(field_type) or self._index.is_enum_type(short):
            return _ada_name(short)
        if self._index.is_message_type(field_type) or self._index.is_message_type(short):
            if short in self._aliases:
                return self._aliases[short]
            return _ada_name(short)
        return _ada_name(short)

    def _ada_field_type(self, field_type: str, repeated: bool,
                        field_name: str) -> Tuple[str, Optional[str]]:
        """Return (ada_type_string, array_type_name_or_None)."""
        base = self._ada_base_type(field_type)
        if repeated:
            arr = _ada_name(field_name) + '_Array'
            return (arr, arr)
        return (base, None)

    def _ada_default(self, ada_type: str, field_type: str) -> Optional[str]:
        """Return Ada default expression, or None if the type has component defaults."""
        short = field_type.split('.')[-1]
        if ada_type in _ADA_DEFAULTS:
            return _ADA_DEFAULTS[ada_type]
        if self._index.is_enum_type(field_type) or self._index.is_enum_type(short):
            enum = (self._index.resolve_enum(field_type)
                    or self._index.resolve_enum(short))
            if enum and enum.values:
                suf = enum.suffix_of(enum.values[0].name)
                val = screaming_to_pascal(suf) if suf else enum.values[0].name
                ada_enum = _ada_name(short)
                prefix = ada_enum.split('_')[-1] + '_'
                return prefix + val
        # Record types rely on their own component defaults — no initialiser needed
        return None

    def _toposort(self, messages: List[ProtoMessage]) -> List[ProtoMessage]:
        names = {m.name for m in messages}
        by_name = {m.name: m for m in messages}
        deps: Dict[str, set] = {}
        for m in messages:
            d = set()
            for f in m.all_fields():
                short = f.type.split('.')[-1]
                if short in names and short != m.name and short not in self._aliases:
                    d.add(short)
            deps[m.name] = d
        order: List[str] = []
        visited: set = set()

        def visit(name: str) -> None:
            if name in visited:
                return
            visited.add(name)
            for dep in deps.get(name, set()):
                visit(dep)
            order.append(name)

        for m in messages:
            visit(m.name)
        return [by_name[n] for n in order]

    def _inline_base_fields(self, msg: ProtoMessage):
        own_names = {f.name for f in msg.fields if f.name != 'base'}
        for field in msg.fields:
            if field.name == 'base' and not field.is_repeated:
                short = field.type.split('.')[-1]
                base_msg = (self._index.resolve_message(field.type)
                            or self._index.resolve_message(short))
                if base_msg and base_msg.name not in self._aliases:
                    for bf in base_msg.fields:
                        name = bf.name
                        if name in own_names:
                            name = short.lower() + '_' + name
                        yield bf, name
                    continue
            yield field, field.name

    def _write_enum(self, f, enum: ProtoEnum) -> None:
        ada_name = _ada_name(enum.name)
        prefix = ada_name.split('_')[-1] + '_'
        f.write(f'   type {ada_name} is\n     (')
        vals = []
        for v in enum.values:
            suf = enum.suffix_of(v.name)
            lit = screaming_to_pascal(suf) if suf else v.name
            vals.append(prefix + lit)
        f.write((',\n      ').join(vals))
        f.write(');\n\n')

    def _arrays_for_msg(self, msg: ProtoMessage) -> List[Tuple[str, str]]:
        """Return [(array_type_name, element_ada_type)] needed by this message."""
        seen: set = set()
        result = []
        for field, fname in self._inline_base_fields(msg):
            if field.is_repeated:
                arr = _ada_name(fname) + '_Array'
                if arr not in seen:
                    seen.add(arr)
                    result.append((arr, self._ada_base_type(field.type)))
        for oo in msg.oneofs:
            for fld in oo.fields:
                if fld.is_repeated:
                    arr = _ada_name(fld.name) + '_Array'
                    if arr not in seen:
                        seen.add(arr)
                        result.append((arr, self._ada_base_type(fld.type)))
        return result

    def _write_record(self, f, msg: ProtoMessage) -> None:
        ada_name = _ada_name(msg.name)
        f.write(f'   type {ada_name} is record\n')
        for field, fname in self._inline_base_fields(msg):
            ada_fname = _ada_name(fname)
            ada_type, arr = self._ada_field_type(field.type, field.is_repeated, fname)
            if arr:
                # Array fields: no initializer (empty by default from type definition)
                f.write(f'      {ada_fname} : {ada_type};\n')
            elif field.is_optional and _ADA_SCALAR_MAP.get(field.type, '') not in (
                    'Unbounded_String', ''):
                f.write(f'      Has_{ada_fname} : Boolean := False;\n')
                dflt = self._ada_default(ada_type, field.type)
                init = f' := {dflt}' if dflt else ''
                f.write(f'      {ada_fname} : {ada_type}{init};\n')
            else:
                dflt = self._ada_default(ada_type, field.type)
                init = f' := {dflt}' if dflt else ''
                f.write(f'      {ada_fname} : {ada_type}{init};\n')
        for oo in msg.oneofs:
            f.write(f'      --  oneof {oo.name}\n')
            for fld in oo.fields:
                ada_fname = _ada_name(fld.name)
                ada_type, _ = self._ada_field_type(fld.type, False, fld.name)
                f.write(f'      Has_{ada_fname} : Boolean := False;\n')
                dflt = self._ada_default(ada_type, fld.type)
                init = f' := {dflt}' if dflt else ''
                f.write(f'      {ada_fname} : {ada_type}{init};\n')
        f.write(f'   end record;\n\n')

    def _write_ads(self, path: Path) -> None:
        alias_names = set(self._aliases.keys())
        non_alias = [m for m in self._index.all_messages()
                     if m.name not in alias_names]
        sorted_msgs = self._toposort(non_alias)

        with open(path, 'w') as f:
            f.write('--  Auto-generated types specification\n')
            f.write(f'--  Generated from: {self._data_model_dir}'
                    f' by ada_service_generator.py --types\n')
            f.write(f'--  Package: {self._ada_pkg}\n\n')
            f.write('with Ada.Strings.Unbounded;  use Ada.Strings.Unbounded;\n\n')
            f.write(f'package {self._ada_pkg} is\n\n')

            # Subtypes for scalar wrappers
            for msg in self._index.all_messages():
                if msg.name in self._aliases:
                    ada_n = _ada_name(msg.name)
                    f.write(f'   subtype {ada_n} is {self._aliases[msg.name]};\n')
            f.write('\n')

            # Enums (always declared before records)
            for enum in self._index.all_enums():
                self._write_enum(f, enum)

            # Array types for scalar/enum elements (no forward-ref risk)
            emitted_arrays: set = set()
            enum_names = {_ada_name(e.name) for e in self._index.all_enums()}
            scalar_types = set(_ADA_SCALAR_MAP.values())
            for msg in sorted_msgs:
                for arr_name, elem_type in self._arrays_for_msg(msg):
                    if arr_name not in emitted_arrays and (
                            elem_type in scalar_types
                            or elem_type in enum_names
                            or elem_type == 'Unbounded_String'):
                        f.write(f'   type {arr_name} is'
                                f' array (Positive range <>) of {elem_type};\n')
                        emitted_arrays.add(arr_name)
            if emitted_arrays:
                f.write('\n')

            # Records interleaved with their array type dependencies
            for msg in sorted_msgs:
                # Emit array types that depend on this record (now it's declared)
                ada_msg_name = _ada_name(msg.name)
                # First write the record itself
                self._write_record(f, msg)
                # Then emit any arrays whose element is this record type
                for later_msg in sorted_msgs:
                    for arr_name, elem_type in self._arrays_for_msg(later_msg):
                        if arr_name not in emitted_arrays and elem_type == ada_msg_name:
                            f.write(f'   type {arr_name} is'
                                    f' array (Positive range <>) of {elem_type};\n')
                            emitted_arrays.add(arr_name)
                            f.write('\n')

            f.write(f'end {self._ada_pkg};\n')


# -- main() -------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print('Usage: python ada_service_generator.py <file.proto|proto_dir> <output_dir>')
        print('       python ada_service_generator.py --codec <file.proto> <output_dir>')
        print('       python ada_service_generator.py --types <data_model_dir>'
              ' <output_dir>')
        sys.exit(1)

    if sys.argv[1] == '--types':
        if len(sys.argv) < 4:
            print('Usage: python ada_service_generator.py --types'
                  ' <data_model_dir> <output_dir>')
            print('  e.g. --types proto/pyramid/data_model examples/ada/generated')
            sys.exit(1)
        gen = AdaTypesGenerator(Path(sys.argv[2]))
        gen.generate(sys.argv[3])
        print('\n\u2713 Ada types generated')
        return

    if sys.argv[1] == '--codec':
        if len(sys.argv) < 4:
            print('Usage: python ada_service_generator.py --codec <file.proto> <output_dir>')
            sys.exit(1)
        parsed = parse_proto(Path(sys.argv[2]))
        gen = JsonCodecGenerator(parsed)
        gen.generate(sys.argv[3])
        print('\n\u2713 JSON codec generated')
        return

    if len(sys.argv) < 3:
        print('Usage: python ada_service_generator.py <file.proto|proto_dir> <output_dir>')
        sys.exit(1)

    gen = AdaServiceGenerator(sys.argv[1])
    gen.generate(sys.argv[2])
    print('\n\u2713 Ada services generated')


if __name__ == '__main__':
    main()
