service_id = "pyramid-subscriber"
service_uuid = "11a5678f-64e9-44c7-a5ca-2cf7da22ff5b"
allowed_topics = ["mission.position-report", "mission.signal-report"]

[[topic_bindings]]
topic = "mission.position-report"
allowed_messages = ["PositionReport"]

[[topic_bindings]]
topic = "mission.signal-report"
allowed_messages = ["SignalReport"]
