service_id = "pyramid-publisher"
service_uuid = "6eefc2b6-08d4-4c39-8267-b1f21745bc90"
allowed_topics = ["mission.position-report", "mission.signal-report"]

[[topic_bindings]]
topic = "mission.position-report"
allowed_messages = ["PositionReport"]

[[topic_bindings]]
topic = "mission.signal-report"
allowed_messages = ["SignalReport"]
